### ISSUE TITLE
depended-on-by.pl returns incorrect results

### ISSUE THREAD

**Issue by karenetheridge** [DrHyde/CPANdeps#41]
http://deps.cpantesters.org/depended-on-by.pl?dist=Module-Build
returns, among other things, MooseX-SlurpyConstructor, but I see no trace of Module::Build in its META.* files. how is it determining this data? Is it looking at an older version of the release? (MXSC used to use Module::Build, but not since 2011.)

**Comment by DrHyde** [comment]
I believe I fixed this bug in https://github.com/DrHyde/CPANdeps/commit/d986968. MooseX-SlurpyConstructor still appears, but quite deep down the tree.
