### ISSUE TITLE
Net::Bluetooth won't install 

### ISSUE THREAD

**Issue by jacoby** [DrHyde/CPANdeps#46]
Writing Makefile for Net::Bluetooth
    Writing MYMETA.yml and MYMETA.json
      ADDUTKO/Net-Bluetooth-0.41.tar.gz
      /home/jacoby/perl5/perlbrew/perls/perl-5.20.2/bin/perl Makefile.PL -- OK
    Running make for A/AD/ADDUTKO/Net-Bluetooth-0.41.tar.gz
    cp Bluetooth.pm blib/lib/Net/Bluetooth.pm
    Running Mkbootstrap for Net::Bluetooth ()
    chmod 644 "Bluetooth.bs"
    "/home/jacoby/perl5/perlbrew/perls/perl-5.20.2/bin/perl" "/home/jacoby/perl5/perlbrew/perls/perl-5.20.2/lib/site_perl/5.20.2/ExtUtils/xsubpp" -prototypes -typemap "/home/jacoby/perl5/perlbrew/perls/perl-5.20.2/lib/5.20.2/ExtUtils/typemap" -typemap "typemap"  Bluetooth.xs > Bluetooth.xsc && mv Bluetooth.xsc Bluetooth.c
    cc -c   -fwrapv -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -O2   -DVERSION=\"0.41\" -DXS_VERSION=\"0.41\" -fPIC "-I/home/jacoby/perl5/perlbrew/perls/perl-5.20.2/lib/5.20.2/i686-linux/CORE"   Bluetooth.c
    Bluetooth.xs:11:33: fatal error: bluetooth/bluetooth.h: No such file or directory
    compilation terminated.
    make: *** [Bluetooth.o] Error 1
      ADDUTKO/Net-Bluetooth-0.41.tar.gz
      /usr/bin/make -- NOT OK

**Comment by DrHyde** [comment]
You need to report that to the author of Net::Bluetooth
