### ISSUE TITLE
error in Installing Module-Metadata-1.000027

### ISSUE THREAD

**Issue by cfcruz08** [DrHyde/CPANdeps#48]
We tried to install Module-Metadata-1.000027 and found the following errors. Hoping for your advise and resolution.
Module-Metadata-1.000027]perl Makefile.PL
Checking if your kit is complete...
Looks good
Warning: prerequisite version 0.87 not found. We have 0.76.
Writing Makefile for Module::Metadata
We can't successfully install the said Modules. We don't know the meaning of the warning in the prerequisite message.

**Comment by DrHyde** [comment]
This is nothing to do with cpandeps
