### ISSUE TITLE
Missing operator  perl Makefile.PL in Proc-Wait3-0.05

### ISSUE THREAD

**Issue by Carlos314** [DrHyde/CPANdeps#54]
Checking if your kit is complete...
Looks good
Bareword found where operator expected at ./Makefile.PL line 1, near "18 gid"
        (Missing operator before gid?)
Number found where operator expected at ./Makefile.PL line 2, near "17"
        (Missing semicolon on previous line?)
Bareword found where operator expected at ./Makefile.PL line 2, near "17 uid"
        (Missing operator before uid?)
Number found where operator expected at ./Makefile.PL line 3, near "20"
        (Missing semicolon on previous line?)
Bareword found where operator expected at ./Makefile.PL line 3, near "20 ctime"
        (Missing operator before ctime?)
Number found where operator expected at ./Makefile.PL line 4, near "20"
        (Missing semicolon on previous line?)
Bareword found where operator expected at ./Makefile.PL line 4, near "20 atime"
        (Missing operator before atime?)
Number found where operator expected at ./Makefile.PL line 5, near "38"
        (Missing semicolon on previous line?)
Bareword found where operator expected at ./Makefile.PL line 5, near "38 LIBARCHIVE"
        (Missing operator before LIBARCHIVE?)
Number found where operator expected at ./Makefile.PL line 6, near "23"
        (Missing semicolon on previous line?)
Bareword found where operator expected at ./Makefile.PL line 6, near "23 SCHILY"
        (Missing operator before SCHILY?)
Number found where operator expected at ./Makefile.PL line 7, near "24"
        (Missing semicolon on previous line?)
Bareword found where operator expected at ./Makefile.PL line 7, near "24 SCHILY"
        (Missing operator before SCHILY?)
Number found where operator expected at ./Makefile.PL line 8, near "18"
        (Missing semicolon on previous line?)
Bareword found where operator expected at ./Makefile.PL line 8, near "18 SCHILY"
        (Missing operator before SCHILY?)
ERROR from evaluation of /export/home/admin/perl_modules/Proc-Wait3-0.05/PaxHeader/Makefile.PL: syntax error at ./Makefile.PL line 1, near "18 gid"

**Comment by DrHyde** [comment]
Please can you tell me how to replicate this bug on the CPANdeps website.
