### ISSUE TITLE
Liberty::Parser Install Error

### ISSUE THREAD

**Issue by Zoaker** [DrHyde/CPANdeps#58]
Hi, 
        I have try to install Liberty::Parser on centos6,  with perl 2.26.1, It comes error with "Can't load '/root/tmp/Liberty-Parser-0.04/blib/lib/liberty.so' for module liberty: /root/tmp/Liberty-Parser-0.04/blib/lib/liberty.so: undefined symbol:Perl_Imarkstack_ptr_ptr at /ic/tools/perl/5.26.1/lib/5.26.1/x86_64-linux/DynaLoader.pm line 193. " I'v try many times but failed, could you help me fix this, thank you!

**Comment by DrHyde** [comment]
You need to talk to the authors of Liberty::Parser.
