### ISSUE TITLE
XML output of non-existent module is malformed

### ISSUE THREAD

**Issue by timsnyder** [DrHyde/CPANdeps#59]
This is probably not that important but if you ask for a module that doesn't exist:
http://deps.cpantesters.org/?xml=1;module=ThisIsNotTheModuleYouAreLookingFor;perl=5.30.0;os=any%20OS;pureperl=1

The site returns malformed XML:
```
            <?xml version="1.0"?>
            <!--
              If you want more/different data, please ask.
            -->
            <cpandeps>
              <module>ThisIsNotAPerlModule</module>
              <perl>5.26</perl>
              <os>any OS</os>
                  </dependency>
            <debug></debug>
            </cpandeps>

```

Note the `</dependency>` tag doesn't have an opening tag.

**Comment by DrHyde** [comment]
Thanks, for letting me know, that definitely needs fixing.

**Comment by DrHyde** [comment]
... and fixed. That was nice and easy :-)
