### ISSUE TITLE
Test results of recent perls are missing

### ISSUE THREAD

**Issue by openstrike** [DrHyde/CPANdeps#60]
Compare the test results shown for Net::SSLeay on [perl 5.28](http://deps.cpantesters.org/?module=Net%3A%3ASSLeay&perl=5.28&os=any+OS) vs [perl 5.30](http://deps.cpantesters.org/?module=Net%3A%3ASSLeay&perl=5.30&os=any+OS). The latter has no test results at all, despite 5.30 being released a year ago.

There are real test results for this as shown at http://matrix.cpantesters.org/?dist=Net-SSLeay so it seems like the data just isn't getting back to CPANdeps somehow.

**Comment by DrHyde** [comment]
Ooh, good catch! And ooh, nasty bug! The test results are actually there, they just got re-mapped to perl **5.3** instead of 5.30-something. Oops. Hopefully some variation on the theme of 7eedc7f should fix it, but fixing the data will take quite some time.

**Comment by DrHyde** [comment]
Initial estimate is 4 days to rebuild the dev site's db so I can make sure everything is OK, then another 4 days to rebuild the main site.

**Comment by DrHyde** [comment]
Rebuild was on track to complete as estimated above, but I've found a few more minor bugs, so starting again.

**Comment by DrHyde** [comment]
Looks good in dev, so now rebuilding the production database. While that's happening you'll still see the tree of dependencies but without complete test results.

**Comment by openstrike** [comment]
Great - thanks. I'm a bit surprised that nobody else spotted this sooner but maybe most people don't go to deps for the test results.

**Comment by DrHyde** [comment]
Aaaaand fixed.
